### ISSUE TITLE
Compiling export template for windows from linux throws an error

### ISSUE THREAD

**Issue by lentsius-bark** [GameAnalytics/GA-SDK-GODOT#10]
Another day, another issue :) GA works now and I'm super happy about that. One last thing that stops me from getting the game to my testers:

Compiling a windows export template from Linux, uses mingw and throws the following error:

```
[ 96%] Linking Program        ==> bin/godot.windows.opt.64.exe
[ 96%] x86_64-w64-mingw32-g++: error: GameAnalytics.lib: No such file or directory
[ 99%] progress_finish(["progress_finish"], [])
[100%] scons: *** [bin/godot.windows.opt.64.exe] Error 1
scons: building terminated because of errors.
```

**Comment by lentsius-bark** [comment]
I should add for more information,
What works:

- compiling the editor with the module works
- compiling a Linux export template works and the template also successfully exports to Linux with functional GA

What doesn't:

- creating an export template for window from Linux using mingw doesn't.

Not sure this is solvable, but as my gitlab CD is based around a Linux headless server(docker image) exporting the game automatically to each target platform, this'd be very welcome.

**Comment by the1schwartz** [comment]
OK thanks for reporting this. I will have a look at this what is going wrong.

**Comment by lentsius-bark** [comment]
Thank you! :)

**Comment by the1schwartz** [comment]
I think you are missing to add the `use_mingw=yes` and maybe also following this https://gameanalytics.atlassian.net/wiki/spaces/ENGINEERING/pages/2147778561/Research+Opt-in+opt-out+flow+in+other+SDKs if you errors with mutex not a member of std namespace.

Let me know if this is working for you.

**Comment by lentsius-bark** [comment]
Although I don't have access to the Confluence documentation, adding the flag use_mingw totally fixed it!
You're a wizard and this issue is solved.
Thank you.
