### ISSUE TITLE
iOS Plugin

### ISSUE THREAD

**Issue by kristijandraca** [GameAnalytics/GA-SDK-GODOT#19]
It would be really great if SDK will take advantage of the Godot Plugin system for iOS as well, so we don't need to recompile.
https://docs.godotengine.org/en/stable/tutorials/platform/ios/ios_plugin.html

**Comment by the1schwartz** [comment]
I have made the SDK available via NativeLib addon now: https://github.com/GameAnalytics/godot-gameanalytics here you don't need to recompile.
