### ISSUE TITLE
Missing Type Specifier and missing ','

### ISSUE THREAD

**Issue by Rdna123** [GameAnalytics/GA-SDK-GODOT#2]
Scons errors due to the problems in the title.

**Comment by the1schwartz** [comment]
Sorry could you post the error you are receiving and for what platform you are building for?

**Comment by Rdna123** [comment]
I will have to reset up  every thing to get the error, but I was building for windows with a portable version of scons.

**Comment by the1schwartz** [comment]
Ok so you fixed the error locally or what did you do? It would nice to know what file I need to look in to find the error.

**Comment by Rdna123** [comment]
This is the error I am receiving.

```
C:\godot-master\modules\gameanalytics\GameAnalytics.h(19): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

C:\godot-master\modules\gameanalytics\GameAnalytics.h(19): error C2143: syntax error: missing ',' before '&'

C:\Users\chknm\TestingGrounds\godot-master\modules\gameanalytics\GameAnalytics.h(20): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

C:\Users\chknm\TestingGrounds\godot-master\modules\gameanalytics\GameAnalytics.h(20): error C2143: syntax error: missing ',' before '&'

C:\godot-master\modules\gameanalytics\GameAnalytics.h(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

C:\godot-master\modules\gameanalytics\GameAnalytics.h(21): error C2143: syntax error: missing ',' before '&'

C:\godot-master\modules\gameanalytics\GameAnalytics.h(23): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

C:\godot-master\modules\gameanalytics\GameAnalytics.h(23): error C2143: syntax error: missing ',' before '&'

C:\godot-master\modules\gameanalytics\GameAnalytics.h(24): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

C:\godot-master\modules\gameanalytics\GameAnalytics.h(24): error C2143: syntax error: missing ',' before '&'

scons: *** [modules\gameanalytics\register_types.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by Rdna123** [comment]
I had not fixed locally, though I am attempting.

It seems though that it is not perceiving PoolStringArray as a specifier.

EDIT:
I am not that advanced with cpp to where I could fix this error.

**Comment by the1schwartz** [comment]
Hmm ok. I have not been able to reproduce the error in my end. What version of Visual Studio are you using and what verison Scons are you using?

**Comment by Rdna123** [comment]
I am using scons-local-4.0.1 and visual studio comunity 2019

**Comment by Rdna123** [comment]
I missed this error before 'cl: Command line warning D9002 : ignoring unknown option '-std=c++11''

I will see if of c++11 is installed on my computer or not

**Comment by the1schwartz** [comment]
I think that is most for mac

**Comment by the1schwartz** [comment]
https://stackoverflow.com/questions/23283080/compiler-error-c4430-missing-type-specifier-int-assumed this suggests it is a circular dependency. I try to fix that

**Comment by the1schwartz** [comment]
Have you added c++ MFC (Microsoft Foundation Class) library? As suggested here: https://godotengine.org/qa/74034/install-from-scratch-compile-error?show=74056

**Comment by Rdna123** [comment]
I don't think that is the problem I can compile it just fine without the module.

The answer provided does not explain a fix.

**Comment by the1schwartz** [comment]
Hmm ok. I am out of ideas. Are you sure you are using a stable version of Godot like stable 3.2.2 (https://github.com/godotengine/godot/releases/tag/3.2.2-stable) and haven't just checked out the latest commit from the master branch?

**Comment by Rdna123** [comment]
It may be how I downloaded the godot files your that I am using portable scons.
