### ISSUE TITLE
error: use of undeclared identifier 'dimension'

### ISSUE THREAD

**Issue by matthew-a-schultz** [GameAnalytics/GA-SDK-GODOT#20]
Attempting to build for MacOS x86 getting the following error:

`modules/gameanalytics/GameAnalytics.cpp:886:34: error: use of undeclared identifier
      'dimension'
    ::setGlobalCustomEventFields(dimension.utf8().get_data());`

**Comment by matthew-a-schultz** [comment]
Looks like this issue is that it's actually passed as "customFields"

**Comment by matthew-a-schultz** [comment]
Added fix to [pull request](https://github.com/GameAnalytics/GA-SDK-GODOT/pull/21)

**Comment by the1schwartz** [comment]
Thanks for reporting this (and creating the PR)
