### ISSUE TITLE
Ad Events

### ISSUE THREAD

**Issue by kristijandraca** [GameAnalytics/GA-SDK-GODOT#22]
Ad Events are currently missing in SDK
https://gameanalytics.com/docs/s/article/Ad-Events-Implementation

**Comment by the1schwartz** [comment]
@kristijandraca I will get ad events added to the SDK

**Comment by the1schwartz** [comment]
Ok there should be a new version out now (v2.3.0) with the ad events added. The documentation page on how to use ad events has also been updated here: https://gameanalytics.com/docs/s/article/Godot-SDK-Event-Tracking

**Comment by kristijandraca** [comment]
Thank you!

**Comment by the1schwartz** [comment]
Of course let me know if you have issues with the newly added ad event
