### ISSUE TITLE
Does not compile for HTML5 export template with Godot 3.4+

### ISSUE THREAD

**Issue by link458** [GameAnalytics/GA-SDK-GODOT#23]
It seems that the referenced file "api/javascript_eval.h" (see GameAnalytics.cpp:6) does not exist in Godot versions as from 3.4; instead there seems to be something somewhat similar in "api/javascript_singleton.h" now but I'm not into Godot and cannot figure out what else needs to change to make it still working.

**Comment by the1schwartz** [comment]
That should be fixed in the latest version (v2.3.3)
