### ISSUE TITLE
(Android) Failed to send events to collector

### ISSUE THREAD

**Issue by Lariay** [GameAnalytics/GA-SDK-GODOT#24]
Hello, on Samsung S10+ I get this warning.
Why it can be?
Maybe you can help me fix it.

02-27 19:41:39.519 28220 28499 W GameAnalytics: Warning/GameAnalytics: Event queue: Failed to send events to collector - Retrying next time
02-27 19:41:48.085 28220 28499 I GameAnalytics: Info/GameAnalytics: Event queue: Sending 113 events.
02-27 19:41:48.492 28220 28499 W GameAnalytics: Warning/GameAnalytics: Event queue: Failed to send events to collector - Retrying next time

**Comment by the1schwartz** [comment]
It looks like there is no internet connection on the device

**Comment by Lariay** [comment]
> It looks like there is no internet connection on the device

But the internet is on :)
This case I never saw on other devices.

**Comment by the1schwartz** [comment]
Ok does any of the previous logs indicate anything to why these warnings appear?

Also does these warning also happen on other devices when you test?

**Comment by Lariay** [comment]
After reinstalling the build all is fine. Strange case.
