### ISSUE TITLE
Example doesn't work on Godot v3.2.2

### ISSUE THREAD

**Issue by ljfantin** [GameAnalytics/GA-SDK-GODOT#3]
I ran the example on Godot v3.2.2 and Godot doesn't load the module 
`if(Engine.has_singleton("GameAnalytics")): ` is false

**Comment by the1schwartz** [comment]
Ok what platform are you building for?

**Comment by lentsius-bark** [comment]
Do you get the message in editor or debug console from mobile?

**Comment by ljfantin** [comment]
I'm building for Android, using Godot 3.2.2.

I/godot   (18273): Loading Android module: org/godotengine/godot/GodotGameAnalytics
E/godot   (18273): **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotGameAnalytics.
E/godot   (18273):    At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.

**Comment by the1schwartz** [comment]
Ok so the issue was that the project.godot file still included this part:

[android]
modules="org/godotengine/godot/GodotGameAnalytics"

Which is not used by the new plugin system (only used by the old way)

I have updated the file as well in the repo.
